import argparse
from pathlib import Path
import torch
import torch.nn.functional as F
from tqdm import tqdm

from belel_hyper_core.distill.belel_evolution_tracker import BelelEvolutionTracker
from belel_hyper_core.belel_denoiser import BelelDenoiser1D


def _load_sd(path: str) -> dict:
    obj = torch.load(path, map_location="cpu")
    if isinstance(obj, dict) and "state_dict" in obj:
        return obj["state_dict"]
    if isinstance(obj, dict):
        return obj
    raise ValueError(f"Unsupported checkpoint format: {path}")


def _load_mel_pt(path: str) -> torch.Tensor:
    obj = torch.load(path, map_location="cpu")
    if isinstance(obj, dict) and "mel" in obj:
        x = obj["mel"]
    else:
        x = obj
    if x.ndim == 3 and x.shape[0] == 1:
        x = x[0]
    if x.ndim != 2 or x.shape[0] != 80:
        raise ValueError(f"Bad mel shape in {path}: {tuple(x.shape)}")
    return x.float()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--student_ckpt", required=True)
    ap.add_argument("--out", default="checkpoints/belel_student_4_evolved.pt")
    ap.add_argument("--device", default="cuda")
    ap.add_argument("--min_score", type=float, default=8.0)
    ap.add_argument("--limit", type=int, default=128)
    ap.add_argument("--epochs", type=int, default=1)
    ap.add_argument("--lr", type=float, default=1e-4)
    ap.add_argument("--batch", type=int, default=8)
    ap.add_argument("--max_len", type=int, default=2048)
    args = ap.parse_args()

    Path("checkpoints").mkdir(exist_ok=True, parents=True)

    items = BelelEvolutionTracker().select(min_score=args.min_score, limit=args.limit)
    if not items:
        raise SystemExit("No scored items found above threshold. Generate with --score first.")

    # Load mel tensors (already generated by Belel)
    mels = []
    for it in items:
        p = Path(it.mel_path)
        if p.exists():
            mels.append(_load_mel_pt(str(p)))
    if not mels:
        raise SystemExit("No mel tensors found on disk. Check mel_path entries.")

    # Student denoiser (fine-tune)
    student = BelelDenoiser1D(channels=32, cond_dim=1024).to(args.device)
    student.load_state_dict(_load_sd(args.student_ckpt), strict=True)
    student.train()

    opt = torch.optim.AdamW(student.parameters(), lr=args.lr)

    # Conditioning placeholder zeros (swap later with real text embeddings)
    # We also need latent tensors; for this loop we fine-tune the denoiser directly
    # on mel-derived pseudo-latents by using a simple learned proxy:
    #
    # IMPORTANT: This loop is “operational minimal.” The correct evolution loop
    # fine-tunes using your codec.encode(mel)->zq. If you want that strict form,
    # we’ll wire codec checkpoint into this script as well.
    #
    # For now: fine-tune denoiser on synthetic latent shaped [B,32,T/4] derived by pooling mel.
    #
    # Next revision should use codec.encode. If you want that now, tell me your codec_ckpt path
    # convention and I’ll lock it in.

    def mel_to_proxy_latent(mel80: torch.Tensor) -> torch.Tensor:
        # mel80: [80,T] -> proxy latent [32,T/4]
        mel = mel80.unsqueeze(0)  # [1,80,T]
        mel = mel[:, :, : args.max_len]
        # downsample time by 4 using avg pooling
        mel_ds = torch.nn.functional.avg_pool1d(mel, kernel_size=4, stride=4)
        # project 80->32 by chunked mean
        chunks = torch.chunk(mel_ds, 32, dim=1)  # 32 chunks ~ 2-3 bins each
        lat = torch.cat([c.mean(dim=1, keepdim=True) for c in chunks], dim=1)  # [1,32,T/4]
        return lat

    # create proxy latents
    latents = [mel_to_proxy_latent(m) for m in mels]

    # training loop
    t_knots = torch.tensor([1.0, 0.66, 0.33, 0.10], device=args.device)  # 4-step student knots

    for ep in range(args.epochs):
        loss_sum = 0.0
        n = 0
        pbar = tqdm(range(0, len(latents), args.batch), desc=f"evolve epoch {ep+1}/{args.epochs}")
        for i in pbar:
            batch = latents[i : i + args.batch]
            x0 = torch.cat(batch, dim=0).to(args.device)  # [B,32,T]
            B = x0.shape[0]
            cond = torch.zeros((B, 1024), device=args.device)

            idx = torch.randint(0, 4, (B,), device=args.device)
            t = t_knots[idx]
            noise = torch.randn_like(x0)
            x = x0 + t.view(-1, 1, 1) * noise

            pred = student(x, t, cond)
            loss = F.mse_loss(pred, noise)

            opt.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(student.parameters(), 1.0)
            opt.step()

            loss_sum += float(loss.item())
            n += 1
            pbar.set_postfix(loss=loss_sum / max(n, 1))

    torch.save({"state_dict": student.state_dict()}, args.out)
    print("saved evolved student:", args.out)


if __name__ == "__main__":
    main()
