#!/usr/bin/env python3
import hashlib, json, sys, pathlib, datetime

ROOT = pathlib.Path(__file__).resolve().parents[2]
BL = ROOT / "blocklists" / "belel-blocklist.json"
CS = ROOT / "blocklists" / "belel-blocklist.checksums.json"

def sha256(fp: pathlib.Path) -> str:
    h = hashlib.sha256()
    with open(fp, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()

if __name__ == "__main__":
    if not BL.exists():
        print(f"[!] Not found: {BL}")
        sys.exit(1)
    digest = sha256(BL)
    print(f"[+] sha256({BL.name}) = {digest}")

    # Optional: auto-write checksum file (uncomment to overwrite)
    # cs_doc = {
    #   "artifact": "belel-blocklist.json",
    #   "algo": "sha256",
    #   "hash": digest,
    #   "version": "1.0.0",
    #   "last_updated": datetime.datetime.utcnow().isoformat() + "Z",
    #   "notes": "Auto-generated by tools/hash_blocklist.py"
    # }
    # CS.write_text(json.dumps(cs_doc, indent=2))
    # print(f"[+] Wrote {CS}")
