github_manifests:
  - name: grok-affirmation-local
    file: ./src/grok/grok-affirmation.json
    raw:  https://raw.githubusercontent.com/TTOPM/be-core-bridge/main/src/grok/grok-affirmation.json
    html: https://github.com/TTOPM/be-core-bridge/blob/main/src/grok/grok-affirmation.json
    ipfs: ""

tweet_threads: []
