name: Sync to Hugging Face

on:
  push:
    branches:
      - main  # change to 'master' if that's your default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Push to Hugging Face
        run: |
          git config --global user.name "Pearce Robinson"
          git config --global user.email "contactme@pearcerobinson.com"
          git remote add hf https://TTOPM:${HF_TOKEN}@huggingface.co/TTOPM/be-core-bridge
          git push hf main --force
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
